//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Authorization {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Authorization.IAuthorization")]
    public interface IAuthorization {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorization/AuthorizeMethod", ReplyAction="http://tempuri.org/IAuthorization/AuthorizeMethodResponse")]
        string AuthorizeMethod(string Login, string Pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorization/AuthorizeMethod", ReplyAction="http://tempuri.org/IAuthorization/AuthorizeMethodResponse")]
        System.Threading.Tasks.Task<string> AuthorizeMethodAsync(string Login, string Pass);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorization/UserInfoMethod", ReplyAction="http://tempuri.org/IAuthorization/UserInfoMethodResponse")]
        string UserInfoMethod(string accessToken);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuthorization/UserInfoMethod", ReplyAction="http://tempuri.org/IAuthorization/UserInfoMethodResponse")]
        System.Threading.Tasks.Task<string> UserInfoMethodAsync(string accessToken);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAuthorizationChannel : Client.Authorization.IAuthorization, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthorizationClient : System.ServiceModel.ClientBase<Client.Authorization.IAuthorization>, Client.Authorization.IAuthorization {
        
        public AuthorizationClient() {
        }
        
        public AuthorizationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthorizationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthorizationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AuthorizeMethod(string Login, string Pass) {
            return base.Channel.AuthorizeMethod(Login, Pass);
        }
        
        public System.Threading.Tasks.Task<string> AuthorizeMethodAsync(string Login, string Pass) {
            return base.Channel.AuthorizeMethodAsync(Login, Pass);
        }
        
        public string UserInfoMethod(string accessToken) {
            return base.Channel.UserInfoMethod(accessToken);
        }
        
        public System.Threading.Tasks.Task<string> UserInfoMethodAsync(string accessToken) {
            return base.Channel.UserInfoMethodAsync(accessToken);
        }
    }
}
