//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Mex_DiskInfo.DiskInfo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MyDiskInfo", Namespace="http://schemas.datacontract.org/2004/07/Service_MyDiskInfo")]
    [System.SerializableAttribute()]
    public partial class MyDiskInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AvailableFreeSpaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DiskNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.IO.DriveType DiskTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FreeSpaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TotalSpaceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Mex_DiskInfo.DiskInfo.User userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AvailableFreeSpace {
            get {
                return this.AvailableFreeSpaceField;
            }
            set {
                if ((object.ReferenceEquals(this.AvailableFreeSpaceField, value) != true)) {
                    this.AvailableFreeSpaceField = value;
                    this.RaisePropertyChanged("AvailableFreeSpace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DiskName {
            get {
                return this.DiskNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DiskNameField, value) != true)) {
                    this.DiskNameField = value;
                    this.RaisePropertyChanged("DiskName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.DriveType DiskType {
            get {
                return this.DiskTypeField;
            }
            set {
                if ((this.DiskTypeField.Equals(value) != true)) {
                    this.DiskTypeField = value;
                    this.RaisePropertyChanged("DiskType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FreeSpace {
            get {
                return this.FreeSpaceField;
            }
            set {
                if ((object.ReferenceEquals(this.FreeSpaceField, value) != true)) {
                    this.FreeSpaceField = value;
                    this.RaisePropertyChanged("FreeSpace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TotalSpace {
            get {
                return this.TotalSpaceField;
            }
            set {
                if ((object.ReferenceEquals(this.TotalSpaceField, value) != true)) {
                    this.TotalSpaceField = value;
                    this.RaisePropertyChanged("TotalSpace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Mex_DiskInfo.DiskInfo.User user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/Service_MyDiskInfo")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client_Mex_DiskInfo.DiskInfo.UserType typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date {
            get {
                return this.DateField;
            }
            set {
                if ((this.DateField.Equals(value) != true)) {
                    this.DateField = value;
                    this.RaisePropertyChanged("Date");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client_Mex_DiskInfo.DiskInfo.UserType type {
            get {
                return this.typeField;
            }
            set {
                if ((this.typeField.Equals(value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserType", Namespace="http://schemas.datacontract.org/2004/07/Service_MyDiskInfo")]
    public enum UserType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Student = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Teacher = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Admin = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DiskInfo.IDiskInfo")]
    public interface IDiskInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskInfo/DiskSpaces", ReplyAction="http://tempuri.org/IDiskInfo/DiskSpacesResponse")]
        Client_Mex_DiskInfo.DiskInfo.MyDiskInfo DiskSpaces(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskInfo/DiskSpaces", ReplyAction="http://tempuri.org/IDiskInfo/DiskSpacesResponse")]
        System.Threading.Tasks.Task<Client_Mex_DiskInfo.DiskInfo.MyDiskInfo> DiskSpacesAsync(string diskName);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IDiskInfo/DiskSpacesWithDescription", ReplyAction = "http://tempuri.org/IDiskInfo/DiskSpacesWithDescriptionResponse", Name = "DiskSpacesWithDescription")]
        Client_Mex_DiskInfo.DiskInfo.MyDiskInfo DiskSpaces(string diskName, string description);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskInfo/DiskSpacesWithDescription", ReplyAction="http://tempuri.org/IDiskInfo/DiskSpacesWithDescriptionResponse", Name = "DiskSpacesWithDescription")]
        System.Threading.Tasks.Task<Client_Mex_DiskInfo.DiskInfo.MyDiskInfo> DiskSpacesAsync(string diskName, string description);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiskInfoChannel : Client_Mex_DiskInfo.DiskInfo.IDiskInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiskInfoClient : System.ServiceModel.ClientBase<Client_Mex_DiskInfo.DiskInfo.IDiskInfo>, Client_Mex_DiskInfo.DiskInfo.IDiskInfo {
        
        public DiskInfoClient() {
        }
        
        public DiskInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiskInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiskInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiskInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Client_Mex_DiskInfo.DiskInfo.MyDiskInfo DiskSpaces(string diskName) {
            return base.Channel.DiskSpaces(diskName);
        }
        
        public System.Threading.Tasks.Task<Client_Mex_DiskInfo.DiskInfo.MyDiskInfo> DiskSpacesAsync(string diskName) {
            return base.Channel.DiskSpacesAsync(diskName);
        }
        
        public Client_Mex_DiskInfo.DiskInfo.MyDiskInfo DiskSpaces(string diskName, string description) {
            return base.Channel.DiskSpaces(diskName, description);
        }
        
        public System.Threading.Tasks.Task<Client_Mex_DiskInfo.DiskInfo.MyDiskInfo> DiskSpacesAsync(string diskName, string description) {
            return base.Channel.DiskSpacesAsync(diskName, description);
        }
    }
}
