//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseUsers
{
    using System;
    using System.Collections.Generic;
    
    public partial class MyUsers
    {
        public int idUser { get; set; }
        public string UName { get; set; }
        public string ULastName { get; set; }
        public string ULogin { get; set; }
        public string Pass { get; set; }
        public string Salt { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> ExpDate { get; set; }
    }
}
