//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Mex_DiskInfo.MyDiskInfo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyDiskInfo.IDiskInfo")]
    public interface IDiskInfo {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskInfo/FreeSpace", ReplyAction="http://tempuri.org/IDiskInfo/FreeSpaceResponse")]
        string FreeSpace(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskInfo/FreeSpace", ReplyAction="http://tempuri.org/IDiskInfo/FreeSpaceResponse")]
        System.Threading.Tasks.Task<string> FreeSpaceAsync(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskInfo/TotalSpace", ReplyAction="http://tempuri.org/IDiskInfo/TotalSpaceResponse")]
        string TotalSpace(string diskName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IDiskInfo/TotalSpace", ReplyAction="http://tempuri.org/IDiskInfo/TotalSpaceResponse")]
        System.Threading.Tasks.Task<string> TotalSpaceAsync(string diskName);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDiskInfoChannel : Client_Mex_DiskInfo.MyDiskInfo.IDiskInfo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiskInfoClient : System.ServiceModel.ClientBase<Client_Mex_DiskInfo.MyDiskInfo.IDiskInfo>, Client_Mex_DiskInfo.MyDiskInfo.IDiskInfo {
        
        public DiskInfoClient() {
        }
        
        public DiskInfoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiskInfoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiskInfoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiskInfoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string FreeSpace(string diskName) {
            return base.Channel.FreeSpace(diskName);
        }
        
        public System.Threading.Tasks.Task<string> FreeSpaceAsync(string diskName) {
            return base.Channel.FreeSpaceAsync(diskName);
        }
        
        public string TotalSpace(string diskName) {
            return base.Channel.TotalSpace(diskName);
        }
        
        public System.Threading.Tasks.Task<string> TotalSpaceAsync(string diskName) {
            return base.Channel.TotalSpaceAsync(diskName);
        }
    }
}
